package extensionrun

import (
	"archive/zip"
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"github.com/nuzur/nuzur-cli/files"
)

const genMarker = "// Code generated by nuzur go-code-gen. DO NOT EDIT.\n\n"

// makeZip builds an in-memory zip from path->content. If manifestFiles is
// non-nil, a generation manifest listing those paths is added.
func makeZip(t *testing.T, entries map[string]string, manifestFiles []string) []byte {
	t.Helper()
	var buf bytes.Buffer
	zw := zip.NewWriter(&buf)
	for name, content := range entries {
		w, err := zw.Create(name)
		if err != nil {
			t.Fatal(err)
		}
		if _, err := w.Write([]byte(content)); err != nil {
			t.Fatal(err)
		}
	}
	if manifestFiles != nil {
		m := files.GeneratedManifest{Version: 1, Generator: "test", Files: manifestFiles}
		data, _ := json.Marshal(m)
		w, err := zw.Create(files.GeneratedManifestFileName)
		if err != nil {
			t.Fatal(err)
		}
		w.Write(data)
	}
	if err := zw.Close(); err != nil {
		t.Fatal(err)
	}
	return buf.Bytes()
}

func read(t *testing.T, dir, rel string) string {
	t.Helper()
	b, err := os.ReadFile(filepath.Join(dir, rel))
	if err != nil {
		t.Fatalf("reading %s: %v", rel, err)
	}
	return string(b)
}

func TestExtractZip_FreshDirWritesEverything(t *testing.T) {
	dir := t.TempDir()
	zip := makeZip(t, map[string]string{
		"core/gen.go": genMarker + "package core\n",
		"app/rest.go": "package app // custom, unmarked\n",
	}, []string{"core/gen.go"})

	if _, err := extractZip(zip, dir); err != nil {
		t.Fatal(err)
	}
	if got := read(t, dir, "core/gen.go"); got != genMarker+"package core\n" {
		t.Errorf("generated file not written: %q", got)
	}
	if got := read(t, dir, "app/rest.go"); got != "package app // custom, unmarked\n" {
		t.Errorf("custom scaffold not written on fresh dir: %q", got)
	}
}

func TestExtractZip_PreservesUserEditsRefreshesGenerated(t *testing.T) {
	dir := t.TempDir()
	// First generation.
	z1 := makeZip(t, map[string]string{
		"core/gen.go": genMarker + "package core // v1\n",
		"app/rest.go": "package app // stub\n",
	}, []string{"core/gen.go"})
	if _, err := extractZip(z1, dir); err != nil {
		t.Fatal(err)
	}
	// User edits their custom file.
	userCode := "package app // MY CUSTOM ENDPOINT\n"
	if err := os.WriteFile(filepath.Join(dir, "app/rest.go"), []byte(userCode), 0o644); err != nil {
		t.Fatal(err)
	}

	// Second generation: server ships a fresh generated file + the empty stub again.
	z2 := makeZip(t, map[string]string{
		"core/gen.go": genMarker + "package core // v2\n",
		"app/rest.go": "package app // stub\n",
	}, []string{"core/gen.go"})
	if _, err := extractZip(z2, dir); err != nil {
		t.Fatal(err)
	}

	if got := read(t, dir, "app/rest.go"); got != userCode {
		t.Errorf("user custom edit was clobbered: %q", got)
	}
	if got := read(t, dir, "core/gen.go"); got != genMarker+"package core // v2\n" {
		t.Errorf("generated file was not refreshed: %q", got)
	}
}

func TestExtractZip_NoManifestOverwritesEverything(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "app.go"), []byte("user code\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	// No manifest → the archive doesn't follow the convention → overwrite all.
	z := makeZip(t, map[string]string{"app.go": "fresh\n"}, nil)
	if _, err := extractZip(z, dir); err != nil {
		t.Fatal(err)
	}
	if got := read(t, dir, "app.go"); got != "fresh\n" {
		t.Errorf("without a manifest, expected overwrite; got %q", got)
	}
}

func TestExtractZip_OrphanGeneratedCleanedUp(t *testing.T) {
	dir := t.TempDir()
	z1 := makeZip(t, map[string]string{
		"a.go": genMarker + "package a\n",
		"b.go": genMarker + "package b\n",
	}, []string{"a.go", "b.go"})
	if _, err := downloadAndExtractLocal(t, z1, dir); err != nil {
		t.Fatal(err)
	}
	// Second run no longer produces b.go.
	z2 := makeZip(t, map[string]string{
		"a.go": genMarker + "package a2\n",
	}, []string{"a.go"})
	if _, err := downloadAndExtractLocal(t, z2, dir); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, "b.go")); !os.IsNotExist(err) {
		t.Errorf("orphaned generated file b.go should have been removed")
	}
}

// downloadAndExtractLocal exercises the extract + manifest-cleanup pipeline
// without HTTP: it mirrors downloadAndExtract's manifest-diff cleanup.
func downloadAndExtractLocal(t *testing.T, data []byte, outputPath string) ([]string, error) {
	t.Helper()
	prev, had, _ := files.ReadGeneratedManifest(outputPath)
	written, err := extractZip(data, outputPath)
	if err != nil {
		return nil, err
	}
	if had {
		cur, hasCur, _ := files.ReadGeneratedManifest(outputPath)
		if hasCur {
			files.CleanupOrphanedGeneratedFiles(outputPath, prev, cur)
		}
	}
	return written, nil
}
