package files

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// GeneratedManifestFileName is the manifest a generator writes at the root of
// its output, listing every file it produced. The CLI uses it to remove files
// that were generated by a previous run but are no longer produced, without
// touching files the user added.
//
// It is keyed off the manifest's presence rather than a specific extension, so
// any extension that emits this manifest gets stale-file cleanup for free.
const GeneratedManifestFileName = ".nuzur-codegen-manifest.json"

// GeneratedManifest is the on-disk manifest format written by a generator.
type GeneratedManifest struct {
	Version     int      `json:"version"`
	Generator   string   `json:"generator"`
	GeneratedAt string   `json:"generated_at"`
	// Files are output-root-relative, forward-slash paths.
	Files []string `json:"files"`
}

// ReadGeneratedManifest reads the manifest from root. The bool reports whether a
// manifest was present; a missing manifest is not an error (a generator that
// doesn't emit one simply opts out of cleanup).
func ReadGeneratedManifest(root string) (GeneratedManifest, bool, error) {
	data, err := os.ReadFile(filepath.Join(root, GeneratedManifestFileName))
	if err != nil {
		if os.IsNotExist(err) {
			return GeneratedManifest{}, false, nil
		}
		return GeneratedManifest{}, false, err
	}
	var m GeneratedManifest
	if err := json.Unmarshal(data, &m); err != nil {
		return GeneratedManifest{}, false, fmt.Errorf("parsing generated manifest: %w", err)
	}
	return m, true, nil
}

// FindGeneratedManifest locates the manifest at or just below outputPath and
// returns the directory that CONTAINS it — which is the root the manifest's
// paths are relative to.
//
// This indirection exists because the extraction root and the manifest root are
// not the same directory. A generator nests its whole output under one folder
// named after the project identifier, so extracting into `nuzur-chorus/` yields
// `nuzur-chorus/chorus/...` with the manifest at `nuzur-chorus/chorus/` and its
// entries relative to THAT ("core/module/...", not "chorus/core/module/...").
// Reading the manifest at outputPath itself therefore finds nothing, and stale
// files are never pruned.
//
// Only outputPath and its immediate subdirectories are considered: that is the
// generator's nesting contract, and a deeper walk risks finding the manifest of
// an unrelated project a user happens to keep inside the workspace. If several
// subdirectories carry a manifest the layout is ambiguous (more than one
// generated project under one root), and it reports not-found rather than guess
// — cleanup is skipped instead of possibly deleting from the wrong tree.
func FindGeneratedManifest(outputPath string) (string, GeneratedManifest, bool, error) {
	// The extraction root itself wins: a flat archive (or a generator that does
	// not nest) puts the manifest here.
	if m, ok, err := ReadGeneratedManifest(outputPath); err != nil {
		return "", GeneratedManifest{}, false, err
	} else if ok {
		return outputPath, m, true, nil
	}

	entries, err := os.ReadDir(outputPath)
	if err != nil {
		if os.IsNotExist(err) {
			return "", GeneratedManifest{}, false, nil
		}
		return "", GeneratedManifest{}, false, err
	}

	var foundRoot string
	var found GeneratedManifest
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		dir := filepath.Join(outputPath, e.Name())
		m, ok, err := ReadGeneratedManifest(dir)
		if err != nil {
			return "", GeneratedManifest{}, false, err
		}
		if !ok {
			continue
		}
		if foundRoot != "" {
			// Ambiguous: two generated projects under one output root.
			return "", GeneratedManifest{}, false, nil
		}
		foundRoot, found = dir, m
	}
	if foundRoot == "" {
		return "", GeneratedManifest{}, false, nil
	}
	return foundRoot, found, true, nil
}

// IsGeneratedFile reports whether the file at path still carries a generated
// marker. It recognizes this generator's marker as well as the standard Go
// "Code generated ... DO NOT EDIT." convention used by tools such as sqlc and
// protoc. A file the user has taken over (and from which the marker was removed)
// returns false, so it is never deleted.
func IsGeneratedFile(path string) bool {
	f, err := os.Open(path)
	if err != nil {
		return false
	}
	defer f.Close()
	// The marker always sits near the top of the file.
	buf := make([]byte, 512)
	n, _ := f.Read(buf)
	head := string(buf[:n])
	return strings.Contains(head, "Code generated") && strings.Contains(head, "DO NOT EDIT")
}

// CleanupOrphanedGeneratedFiles removes files that were produced by a previous
// generation (listed in previous) but are no longer produced by the current one
// (absent from current). A file is removed only when it still carries the
// generated marker, so:
//
//   - files the user added (never in a manifest, never marked) are never touched;
//   - files the user took over by editing out the marker are never touched;
//   - files still generated by the current run are kept (already overwritten).
//
// Directories left empty by the removals are pruned. It returns the list of
// removed paths (output-root-relative), and is best-effort: an error removing
// one file is returned but does not undo prior removals.
func CleanupOrphanedGeneratedFiles(root string, previous, current GeneratedManifest) ([]string, error) {
	currentSet := make(map[string]struct{}, len(current.Files))
	for _, f := range current.Files {
		currentSet[f] = struct{}{}
	}

	var removed []string
	var touchedDirs []string
	for _, rel := range previous.Files {
		if _, stillGenerated := currentSet[rel]; stillGenerated {
			continue
		}
		abs := filepath.Join(root, filepath.FromSlash(rel))
		info, err := os.Stat(abs)
		if err != nil || info.IsDir() {
			continue // already gone, or not a regular file
		}
		// Safety net: only delete files that are still recognizably generated.
		if !IsGeneratedFile(abs) {
			continue
		}
		if err := os.Remove(abs); err != nil {
			return removed, fmt.Errorf("removing orphaned generated file %s: %w", rel, err)
		}
		removed = append(removed, rel)
		touchedDirs = append(touchedDirs, filepath.Dir(abs))
	}

	pruneEmptyDirs(root, touchedDirs)
	return removed, nil
}

// pruneEmptyDirs removes directories that became empty as a result of deletions,
// walking upward from each touched directory but never removing root itself or
// stepping outside it.
func pruneEmptyDirs(root string, dirs []string) {
	absRoot, err := filepath.Abs(root)
	if err != nil {
		return
	}
	for _, d := range dirs {
		cur, err := filepath.Abs(d)
		if err != nil {
			continue
		}
		for cur != absRoot && strings.HasPrefix(cur, absRoot+string(os.PathSeparator)) {
			entries, err := os.ReadDir(cur)
			if err != nil || len(entries) > 0 {
				break
			}
			if err := os.Remove(cur); err != nil {
				break
			}
			cur = filepath.Dir(cur)
		}
	}
}
