package files

import (
	"encoding/json"
	"os"
	"path/filepath"
	"sort"
	"testing"
)

const goMarker = "// Code generated by nuzur go-code-gen. DO NOT EDIT.\n\n"

func writeFile(t *testing.T, root, rel, content string) {
	t.Helper()
	abs := filepath.Join(root, filepath.FromSlash(rel))
	if err := os.MkdirAll(filepath.Dir(abs), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(abs, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

func writeManifest(t *testing.T, root string, files ...string) {
	t.Helper()
	m := GeneratedManifest{Version: 1, Generator: "nuzur go-code-gen", Files: files}
	data, _ := json.MarshalIndent(m, "", "  ")
	if err := os.WriteFile(filepath.Join(root, GeneratedManifestFileName), data, 0o644); err != nil {
		t.Fatal(err)
	}
}

func exists(root, rel string) bool {
	_, err := os.Stat(filepath.Join(root, filepath.FromSlash(rel)))
	return err == nil
}

func TestCleanupOrphanedGeneratedFiles(t *testing.T) {
	root := t.TempDir()

	// Previous run produced these (all marked generated).
	writeFile(t, root, "core/core.go", goMarker+"package core\n")
	writeFile(t, root, "core/module/old_entity/list.go", goMarker+"package old_entity\n") // becomes orphan
	writeFile(t, root, "core/module/old_entity/delete.go", goMarker+"package old_entity\n")
	writeFile(t, root, "rest/server/server.go", goMarker+"package server\n") // becomes orphan
	// A previously-generated file the user has taken over (marker removed).
	writeFile(t, root, "core/module/old_entity/custom_logic.go", "package old_entity // my own code\n")
	previous := GeneratedManifest{Files: []string{
		"core/core.go",
		"core/module/old_entity/list.go",
		"core/module/old_entity/delete.go",
		"core/module/old_entity/custom_logic.go",
		"rest/server/server.go",
	}}

	// A file the user added that the generator never produced.
	writeFile(t, root, "core/my_helpers.go", "package core // user added\n")

	// Current run only produces core/core.go (rest disabled, entity removed).
	writeManifest(t, root, "core/core.go")
	current, ok, err := ReadGeneratedManifest(root)
	if err != nil || !ok {
		t.Fatalf("ReadGeneratedManifest: ok=%v err=%v", ok, err)
	}

	removed, err := CleanupOrphanedGeneratedFiles(root, previous, current)
	if err != nil {
		t.Fatalf("cleanup error: %v", err)
	}

	sort.Strings(removed)
	want := []string{
		"core/module/old_entity/delete.go",
		"core/module/old_entity/list.go",
		"rest/server/server.go",
	}
	if len(removed) != len(want) {
		t.Fatalf("removed = %v, want %v", removed, want)
	}
	for i := range want {
		if removed[i] != want[i] {
			t.Fatalf("removed = %v, want %v", removed, want)
		}
	}

	// Still-generated file kept.
	if !exists(root, "core/core.go") {
		t.Error("core/core.go (still generated) must be kept")
	}
	// User-added file kept.
	if !exists(root, "core/my_helpers.go") {
		t.Error("user-added file must be kept")
	}
	// User-took-over file (marker removed) kept — the key safety rule.
	if !exists(root, "core/module/old_entity/custom_logic.go") {
		t.Error("file with the marker removed by the user must NOT be deleted")
	}
	// Orphans removed.
	if exists(root, "rest/server/server.go") {
		t.Error("orphaned generated file should be removed")
	}
	// The rest/server dir held only generated files -> pruned.
	if exists(root, "rest/server") || exists(root, "rest") {
		t.Error("directory left empty after cleanup should be pruned")
	}
	// old_entity dir still has the user's custom file -> NOT pruned.
	if !exists(root, "core/module/old_entity") {
		t.Error("directory still containing a user file must not be pruned")
	}
}

func TestReadGeneratedManifestAbsent(t *testing.T) {
	root := t.TempDir()
	_, ok, err := ReadGeneratedManifest(root)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if ok {
		t.Fatal("expected ok=false when no manifest is present")
	}
}

func TestIsGeneratedFile(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "gen.go", goMarker+"package x\n")
	writeFile(t, root, "sqlc.go", "// Code generated by sqlc. DO NOT EDIT.\npackage x\n")
	writeFile(t, root, "user.go", "package x // hand written\n")

	if !IsGeneratedFile(filepath.Join(root, "gen.go")) {
		t.Error("marked file should be detected as generated")
	}
	if !IsGeneratedFile(filepath.Join(root, "sqlc.go")) {
		t.Error("sqlc-marked file should be detected as generated")
	}
	if IsGeneratedFile(filepath.Join(root, "user.go")) {
		t.Error("unmarked user file must not be detected as generated")
	}
}
